# fly.toml app configuration file generated for gaming-companies-guardian-pb on 2023-07-01T17:06:50+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gaming-companies-guardian-pb"
primary_region = "hkg"

[http_service]
  internal_port = 8090
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source = "pb_data"
  destination = "pocketbase/pb_data"
